--- Basic SELECT Queries
SELECT *
FROM customers
LIMIT 10;

SELECT *
FROM orders
LIMIT 10;

SELECT COUNT(*)
FROM customers;

SELECT order_status,
       COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;

SELECT c.customer_id,
       o.order_status
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
LIMIT 10;

SELECT SUM(payment_value)
FROM payments;

SELECT payment_type,
       ROUND(SUM(payment_value)::numeric, 2) AS revenue
FROM payments
GROUP BY payment_type
ORDER BY revenue DESC;

SELECT seller_id,
       COUNT(*) AS total_sales
FROM order_items
GROUP BY seller_id
ORDER BY total_sales DESC
LIMIT 10;

-- Group By & HAVING
-- Top 10 cities with the most customers

SELECT customer_city,
       COUNT(*) AS total_customers
FROM customers
GROUP BY customer_city
ORDER BY total_customers DESC
LIMIT 10;

-- States generating the most orders

SELECT customer_state,
       COUNT(*) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC;

-- Payment methods contributing more than 100000 transactions

SELECT payment_type,
       COUNT(*) AS total_transactions
FROM payments
GROUP BY payment_type
HAVING COUNT(*) > 100000;

-- JOINs
-- Orders with customer location

SELECT o.order_id,
       c.customer_city,
       c.customer_state
FROM orders o
INNER JOIN customers c
ON o.customer_id = c.customer_id
LIMIT 10;

-- Order amount for each order

SELECT p.order_id,
       SUM(p.payment_value) AS total_amount
FROM payments p
GROUP BY p.order_id
LIMIT 10;

-- Revenue generated by each state

SELECT c.customer_state,
       ROUND(SUM(p.payment_value)::numeric,2) AS revenue
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
INNER JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_state
ORDER BY revenue DESC;

-- Multi-table JOINs
-- Subqueries and CTEs

WITH customer_revenue AS (
    SELECT c.customer_id,
           SUM(p.payment_value) AS revenue
    FROM customers c
    JOIN orders o
    ON c.customer_id=o.customer_id
    JOIN payments p
    ON o.order_id=p.order_id
    GROUP BY c.customer_id
)

SELECT *
FROM customer_revenue
ORDER BY revenue DESC
LIMIT 10;

-- How many orders does each customer have?

SELECT
    c.customer_id,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY total_orders DESC;

-- Revenue by state

SELECT
    c.customer_state,
    ROUND(SUM(p.payment_value)::numeric,2) AS revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_state
ORDER BY revenue DESC;

-- Top 10 customers by spending

SELECT
    c.customer_id,
    ROUND(SUM(p.payment_value)::numeric,2) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_id
ORDER BY total_spent DESC
LIMIT 10;

-- CASE WHEN

SELECT
    payment_value,
    CASE
        WHEN payment_value > 100 THEN 'High'
        ELSE 'Low'
    END AS payment_category
FROM payments
LIMIT 10;

-- CTEs

WITH revenue_table AS (
    SELECT
        c.customer_id,
        SUM(p.payment_value) AS revenue
    FROM customers c
    JOIN orders o
    ON c.customer_id = o.customer_id
    JOIN payments p
    ON o.order_id = p.order_id
    GROUP BY c.customer_id
)

SELECT *
FROM revenue_table
ORDER BY revenue DESC
LIMIT 10;

-- Window Functions

WITH category_revenue AS (
    SELECT
        ct.product_category_name_english,
        ROUND(SUM(p.payment_value)::numeric,2) AS revenue
    FROM products pr
    JOIN category_translation ct
        ON pr.product_category_name = ct.product_category_name
    JOIN order_items oi
        ON pr.product_id = oi.product_id
    JOIN payments p
        ON oi.order_id = p.order_id
    GROUP BY ct.product_category_name_english
)

SELECT
    product_category_name_english,
    revenue,
    DENSE_RANK() OVER (
        ORDER BY revenue DESC
    ) AS category_rank
FROM category_revenue
LIMIT 20;

-- window function

WITH monthly_revenue AS (
    SELECT
        DATE_TRUNC(
            'month',
            CAST(order_purchase_timestamp AS timestamp)
        ) AS month,
        ROUND(SUM(payment_value)::numeric,2) AS revenue
    FROM orders o
    JOIN payments p
        ON o.order_id = p.order_id
    GROUP BY month
)

SELECT
    month,
    revenue,
    LAG(revenue) OVER (
        ORDER BY month
    ) AS previous_month_revenue
FROM monthly_revenue;